language: android

android:
  components:
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - ".+"
  
jdk:
- oraclejdk8

script: if [[ "$TRAVIS_BRANCH" == "master" ]]; then ./gradlew clean :app:assembleRelease --stacktrace; else ./gradlew clean test --stacktrace; fi

sudo: required

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

before_script:
- chmod +x gradlew

before_install:
- yes | sdkmanager "platforms;android-27"

before_deploy:
  ##- git tag -f "travis-build"
  - git config --local user.name "ramachandar.s"
  - git config --local user.email "ramachandar.s@hcl.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  
deploy:
  provider: releases
  api_key: b1ae23474bce97396c367aa071b993e7d5abc8e8
  file_glob: true
  file: $TRAVIS_BUILD_DIR/app/build/outputs/apk/release/*.apk
  skip_cleanup: true
  overwrite: true
  prerelease: true
  target_commitsh: $TRAVIS_COMMIT
  on:
    branch: master
    repo: rams3073/travisRepo
    
after_deploy:
  - rm -rf $TRAVIS_BUILD_DIR/app/build/outputs
